version: '3'
services:
    server:
        build: ./server
        ports:
            - 3000:8888
        volumes:
            - ./server:/go/src/app
    client:
        build: ./client
        ports:
            - 8080:8080
        volumes:
            - ./client:/app
        command: yarn serve

    web:
        image: nginx:1.17-alpine
        depends_on:
            - server
        ports:
            - 10080:80
        volumes:
            - ./server:/work
            - ./logs:/var/log/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        environment:
            - TZ=Asia/Tokyo

    db:
        image: mysql:8.0
        volumes:
            - db-store:/var/lib/mysql
            - ./logs:/var/log/mysql
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./mysql/init:/docker-entrypoint-initdb.d/
        environment:
            - MYSQL_DATABASE=photoapp
            - MYSQL_USER=ono
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
            - TZ=Asia/Tokyo

volumes:
    db-store:

