version: '3'
services:
    server:
        build: ./server
        ports:
            - 8888:8888
        volumes:
            - ./server:/go/src/app
    client:
        build: ./client
        ports:
            - 8080:8080
        volumes:
            - ./client:/app
        command: yarn serve
