version: "3"
services:
  server:
    build: ./server
    ports:
      - 8888:8888
    depends_on:
      - db
    volumes:
      - ./server:/go/src/app
        - ./public:/go/src/app/public
    env_file:
      - ./server/.env
    restart: always

  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
      - ./public:/app/public
    command: yarn serve

  db:
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    env_file:
      - mysql/.env

volumes:
  db-store:
