apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: myksa
      containers:
        - name: imagechat-backend
          image: gcr.io/imagechat-285706/imagechat-backend:8c370119b94da783872872a9d51fae1e85a8d69e
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-info
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-info
                  key: db_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-info
                  key: db_name
            - name: ENV_TYPE
              value: prod
            - name: BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: tf-output
                  key: bucket-name
          resources:
            limits:
              memory: "1000Mi"
              cpu: "300m"
            requests:
              memory: "250Mi"
              cpu: "10m"
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8888
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          env:
            - name: CONNECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: tf-output
                  key: cloudsql-connection-name
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-instances=$(CONNECTION_NAME)=tcp:3306"
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "10m"
          securityContext:
            runAsNonRoot: true
