apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: imagechat-frontend
        image: gcr.io/imagechat-285706/imagechat-frontend:8c370119b94da783872872a9d51fae1e85a8d69e
        resources:
          limits:
            memory: "1000Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
