apiVersion: v1
kind: Service
metadata:
  name: vue-nginx
spec:
  type: LoadBalancer
  selector:
    app: vue-nginx
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-nginx
  template:
    metadata:
      labels:
        app: vue-nginx
    spec:
      containers:
      - name: vue-nginx
        image: gcr.io/photoapp-267210/client
        ports:
        - containerPort: 80
          name: vue-nginx

