steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/server:1.0', '-f', 'Dockerfile.prod', './server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/db:1.0', '../mysql']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/web:1.0', '-f', 'Dockerfile.prod', './nginx']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/client:1.0', '-f', 'Dockerfile.prod', './client']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'secret', 'generic', 'server-secret', '--from-file=./server/.env']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['create', 'secret', 'generic', 'mysql-secret', '--from-file=./mysql/.env']

images: ['gcr.io/$PROJECT_ID/server:1.0', 'gcr.io/$PROJECT_ID/db:1.0', 'gcr.io/$PROJECT_ID/web:1.0', 'gcr.io/$PROJECT_ID/client:1.0']
