apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: storage-key
      containers:
      - image: gcr.io/photoapp-267210/server
        name: server
        ports:
        - containerPort: 8888
          name: server
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: MYSQL_USER
          - name: MYSQL_HOST
            value: db
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: dbsecret
                key: MYSQL_DATABASE
          - name: ENV_TYPE
            value: prod
          - name: BUCKET_NAME
            value: hitsuji
      - image: gcr.io/photoapp-267210/web
        name: web
        ports:
        - containerPort: 80
          name: web

